### ISSUE TITLE
Requests providing account details should provide entire block.

### ISSUE THREAD

**Issue by MurrayGroves** [MurrayGroves/MurraxCoin#17]
Functions such as `getBalance()` should return the whole block which they got their info from, not just the value. This means that the recipient can cryptographically verify the response themselves, rather than trusting that the node gave the correct value.

**Comment by ethrx** [comment]
Why?

**Comment by ethrx** [comment]
I disagree

**Comment by MurrayGroves** [comment]
After further thoughts, this seems unnecessary. If a client wants to be absolutely certain it can trust a node, it should run its own node.
