### ISSUE TITLE
No validation on getRepresentative

### ISSUE THREAD

**Issue by atotmix** [MurrayGroves/MurraxCoin#39]
This allows people to spoof send transactions as the only validation on the send command is the representative

EDIT: Found by @ethrx

**Comment by MurrayGroves** [comment]
Issue is that inside of transaction validation, the signature is checked for validity. However, a `return` statement is missing, causing the transaction to continue, regardless of the validity of the signature.

**Comment by ethrx** [comment]
Found by security researcher @ethrx. Donations welcome: mxc_pbquwvu4hsjp5qi6pamjr5ulweaoiqicfh33fwn5tvbdldyxpldq7zha7jq

**Comment by atotmix** [comment]
This is true ^
