### ISSUE TITLE
Ledger is requested from multiple nodes.

### ISSUE THREAD

**Issue by MurrayGroves** [MurrayGroves/MurraxCoin#5]
On boot, the ledger should be requested from multiple nodes, and if disagreed upon, more nodes should be requested from and a ledger shall be agreed on by voting weight.

**Comment by MurrayGroves** [comment]
boot sequence follows:
- generate hashes of all account files
- send to nodes with most (last known) voting power
- nodes respond with which ones don't match their stored hash and what their stored hash is.
- node chooses which hash to "believe" based on voting power of the nodes that supplied it.
- node sends its most recent block for each changed account to each node that supplied the chosen hash.
- each node responds with all the blocks that came after.
- if the nodes send different data, once again choose based on voting power and validity. If all of the nodes send the same invalid blocks, choose the next best hash and repeat.
- update local ledger with new blocks

**Comment by ethrx** [comment]
pls fix!!

**Comment by MurrayGroves** [comment]
> pls fix!!

It's really complicated :(
